"""Portable no-live Memory Seam core package."""

from importlib.metadata import PackageNotFoundError, version

from .adapters import *  # noqa: F401,F403
from .atlas_query_bridge import *  # noqa: F401,F403
from .confidentiality_classification import *  # noqa: F401,F403
from .contracts import *  # noqa: F401,F403
from .custody_receipts import *  # noqa: F401,F403
from .descriptors import *  # noqa: F401,F403
from .policy import *  # noqa: F401,F403
from .positive_authorization_receipt import *  # noqa: F401,F403
from .providers import *  # noqa: F401,F403
from .receipts import *  # noqa: F401,F403
from .l5_bounded_runner import *  # noqa: F401,F403
from .l5_post_read_verifier import *  # noqa: F401,F403
from .router import *  # noqa: F401,F403
from .runtime import *  # noqa: F401,F403
from .supervised_source_card_preflight import *  # noqa: F401,F403
from .testing import *  # noqa: F401,F403
from .write_custody_approval import *  # noqa: F401,F403
from .write_custody_operation_classes import *  # noqa: F401,F403
from .write_custody_rollback_audit import *  # noqa: F401,F403
from .write_intent_preflight_gate import *  # noqa: F401,F403

try:
    __version__ = version("memory-seam")
except PackageNotFoundError:
    __version__ = "0.1.0"

__all__ = [
    "__version__",
    "ADAPTER_PROTOCOL_VERSION",
    "ATLAS_QUERY_BRIDGE_CONTRACT_VERSION",
    "ATLAS_QUERY_BRIDGE_CONTRACT_COMPATIBILITY",
    "ATLAS_QUERY_BRIDGE_CONTRACT_MAJOR",
    "ATLAS_QUERY_BRIDGE_CONTRACT_SCHEMA",
    "ATLAS_QUERY_BRIDGE_STATUS",
    "ATLAS_QUERY_HELD_SURFACES",
    "ATLAS_QUERY_PROVIDER_METHODS",
    "ATLAS_QUERY_REQUIRED_EXPORTS",
    "ATLAS_QUERY_ROUTE_PROBES",
    "AdapterMemorySeamProvider",
    "BoundedReadGrant",
    "BoundedRunnerConfig",
    "BoundedRunnerConfigError",
    "BoundedRunnerPosture",
    "AtlasQueryBridgeContractFixture",
    "AtlasQueryBridgePlan",
    "AtlasQueryRouteBridge",
    "CONFIDENTIALITY_CLASSIFICATION_ALLOWED",
    "CONFIDENTIALITY_CLASSIFICATION_WITHHELD",
    "CONFIDENTIALITY_RAW_SESSION_MARKERS",
    "ConfidentialityClassificationVerdict",
    "CONTRACT_STATUS",
    "CONTEXT_SCOPE_PREFIX",
    "DIARY_READ_CEILING_FLEET",
    "DIARY_READ_CEILING_SELF",
    "VALID_DIARY_READ_CEILINGS",
    "L6_CUSTODY_RECEIPT_ALLOWED_SHAPES",
    "L6_CUSTODY_RECEIPT_HELD_SURFACES",
    "L6_CUSTODY_RECEIPT_NOOP_FIXTURES",
    "L6_CUSTODY_RECEIPT_REQUIRED_FIELDS",
    "L6_CUSTODY_RECEIPT_SCHEMA_VERSION",
    "L6_CUSTODY_RECEIPT_STATUS",
    "L6_POSITIVE_AUTHORIZATION_APPROVAL_AUTHOR_ASSOCIATION",
    "L6_POSITIVE_AUTHORIZATION_APPROVAL_CREATED_AT",
    "L6_POSITIVE_AUTHORIZATION_APPROVAL_EXPIRES_AT",
    "L6_POSITIVE_AUTHORIZATION_APPROVAL_ISSUE",
    "L6_POSITIVE_AUTHORIZATION_APPROVAL_PACKET",
    "L6_POSITIVE_AUTHORIZATION_APPROVAL_PHRASE_SHA256",
    "L6_POSITIVE_AUTHORIZATION_APPROVAL_REF",
    "L6_POSITIVE_AUTHORIZATION_APPROVAL_SOURCE_URL",
    "L6_POSITIVE_AUTHORIZATION_DENIAL_STATUS",
    "L6_POSITIVE_AUTHORIZATION_GUARDED_COUNTERS",
    "L6_POSITIVE_AUTHORIZATION_HELD_SURFACES",
    "L6_POSITIVE_AUTHORIZATION_IMPLEMENTATION_ACTOR_ROLE",
    "L6_POSITIVE_AUTHORIZATION_MAX_OPERATION_COUNT",
    "L6_POSITIVE_AUTHORIZATION_RECEIPT_SCHEMA_VERSION",
    "L6_POSITIVE_AUTHORIZATION_RECEIPT_SLICE",
    "L6_POSITIVE_AUTHORIZATION_RECEIPT_STATUS",
    "L6_POSITIVE_AUTHORIZATION_REPORT_SAFETY",
    "L6_POSITIVE_AUTHORIZATION_REQUIRED_APPROVAL_FIELDS",
    "L6_WRITE_CUSTODY_APPROVAL_FIXTURES",
    "L6_WRITE_CUSTODY_APPROVAL_REQUIRED_FIELDS",
    "L6_WRITE_CUSTODY_APPROVAL_SCHEMA_VERSION",
    "L6_WRITE_CUSTODY_APPROVAL_STATUS",
    "L6_WRITE_CUSTODY_HELD_SURFACES",
    "L6_WRITE_CUSTODY_OPERATION_CLASSES",
    "L6_WRITE_CUSTODY_OPERATION_CLASS_FIXTURES",
    "L6_WRITE_CUSTODY_OPERATION_CLASS_HELD_SURFACES",
    "L6_WRITE_CUSTODY_OPERATION_CLASS_NAMES",
    "L6_WRITE_CUSTODY_OPERATION_CLASS_REQUIRED_FIELDS",
    "L6_WRITE_CUSTODY_OPERATION_CLASS_SCHEMA_VERSION",
    "L6_WRITE_CUSTODY_OPERATION_CLASS_STATUS",
    "L6_WRITE_CUSTODY_REQUIRED_APPROVAL_FIELDS",
    "L6_WRITE_CUSTODY_ROLLBACK_AUDIT_FIXTURE",
    "L6_WRITE_CUSTODY_ROLLBACK_AUDIT_HELD_SURFACES",
    "L6_WRITE_CUSTODY_ROLLBACK_AUDIT_OPERATION_CLASSES",
    "L6_WRITE_CUSTODY_ROLLBACK_AUDIT_REQUIRED_AUDIT_FIELDS",
    "L6_WRITE_CUSTODY_ROLLBACK_AUDIT_REQUIRED_FAILURE_MODES",
    "L6_WRITE_CUSTODY_ROLLBACK_AUDIT_REQUIRED_FIELDS",
    "L6_WRITE_CUSTODY_ROLLBACK_AUDIT_REQUIRED_STOP_CONDITIONS",
    "L6_WRITE_CUSTODY_ROLLBACK_AUDIT_SCHEMA_VERSION",
    "L6_WRITE_CUSTODY_ROLLBACK_AUDIT_STATUS",
    "L6_WRITE_INTENT_DENIAL_REASON",
    "L6_WRITE_INTENT_DENIAL_RECEIPT_SCHEMA_VERSION",
    "L6_WRITE_INTENT_APPROVAL_CONTEXT_REQUIRED_FIELDS",
    "L6_WRITE_INTENT_GUARDED_COUNTERS",
    "L6_WRITE_INTENT_HELD_SURFACES",
    "L6_WRITE_INTENT_MAX_SYNTHETIC_OPERATIONS",
    "L6_WRITE_INTENT_OPERATION_CLASS",
    "L6_WRITE_INTENT_PREFLIGHT_GATE_APPROVAL_REF",
    "L6_WRITE_INTENT_PREFLIGHT_GATE_APPROVAL_ISSUE",
    "L6_WRITE_INTENT_PREFLIGHT_GATE_APPROVAL_AUTHOR_ASSOCIATION",
    "L6_WRITE_INTENT_PREFLIGHT_GATE_APPROVAL_CREATED_AT",
    "L6_WRITE_INTENT_PREFLIGHT_GATE_APPROVAL_EXPIRES_AT",
    "L6_WRITE_INTENT_PREFLIGHT_GATE_FIXTURE",
    "L6_WRITE_INTENT_PREFLIGHT_GATE_ROLLBACK_REF",
    "L6_WRITE_INTENT_PREFLIGHT_GATE_SCHEMA_VERSION",
    "L6_WRITE_INTENT_PREFLIGHT_GATE_SLICE",
    "L6_WRITE_INTENT_PREFLIGHT_GATE_STATUS",
    "L6_WRITE_INTENT_REPORT_SAFETY",
    "ContextProvider",
    "DOGFOOD_USEFULNESS_STATUS",
    "DenyAllIdentityVerifier",
    "ContextReadKillSwitch",
    "ContextSource",
    "ContextSourceAllowlist",
    "ContextSourceDescriptor",
    "ContextSourceDescriptorRegistry",
    "ContextSourceGrant",
    "ContextSourceGrantMatrix",
    "ContextSourceReadResult",
    "HealthProvider",
    "IdentityDecision",
    "IdentityVerifier",
    "L5_BOUNDED_RUNNER_HELD_SURFACES",
    "L5_BOUNDED_RUNNER_MAX_TICKS",
    "L5_BOUNDED_RUNNER_SCHEMA",
    "L5_BOUNDED_RUNNER_STATUS",
    "L5_POST_READ_VERIFIER_SCHEMA",
    "L5_RECEIPT_SCHEMA",
    "LocalReadOnlyRuntime",
    "MemorySeamProvider",
    "NullMemorySeamProvider",
    "PositiveAuthorizationCallbackHarness",
    "READ_ENDPOINTS",
    "RUNTIME_AUDIT_RECEIPT_VERSION",
    "RUNTIME_HELD_SURFACES",
    "RUNTIME_STATUS",
    "ReadOnlyRuntimeConfig",
    "RecallProvider",
    "RuntimeRequest",
    "RunnerRuntime",
    "SAFE_DOGFOOD_ITEMS",
    "SAFE_SOURCE_CARD_ADAPTER_STATUS",
    "SAFE_SOURCE_CARDS",
    "SYNTHETIC_RECALL_RANKING_FIXTURE_VERSION",
    "SYNTHETIC_USEFULNESS_RUBRIC_VERSION",
    "SourceAdapter",
    "SourceCard",
    "SourceCardAdapter",
    "SourceReadPlan",
    "SyntheticSourceCardAdapter",
    "assert_source_card_is_report_safe",
    "StaticIdentityVerifier",
    "SubjectPolicy",
    "SyntheticSafeContentAdapter",
    "VALID_CONTEXT_INCLUDES",
    "VALID_SCOPES",
    "WRITE_LIKE_ROUTES",
    "WriteIntentPreflightCallbackHarness",
    "agent_matches_subject",
    "assert_atlas_query_bridge_contract",
    "atlas_query_bridge_contract_fixture",
    "atlas_query_bridge_plan",
    "atlas_query_route_bridge",
    "build_read_receipt",
    "build_l6_custody_receipt_noop_fixtures",
    "build_l6_positive_authorization_approval_context_fixture",
    "build_l6_positive_authorization_receipt_metadata",
    "build_l6_write_custody_approval_fixtures",
    "build_l6_write_custody_operation_class_fixtures",
    "build_l6_write_custody_rollback_audit_fixture",
    "build_l6_write_intent_denial_receipt_metadata",
    "build_l6_write_intent_approval_context_fixture",
    "build_l6_write_intent_preflight_gate_fixture",
    "build_runtime_audit_receipt",
    "classify_confidentiality",
    "context_scope_allowed",
    "context_source_descriptor_id",
    "cross_agent_read_permitted",
    "describe_context_source_descriptors",
    "effective_source_subject",
    "kill_switch_denial_for",
    "kill_switch_snapshot",
    "policy",
    "provider_handlers",
    "parse_write_intent_operation_class",
    "read_receipt_enabled",
    "rank_synthetic_recall_items",
    "replay_read_receipt",
    "route_request",
    "run_positive_authorization_receipt_skeleton",
    "run_write_intent_preflight_gate",
    "run_bounded_read_ticks",
    "runtime_health",
    "scope_allowed",
    "scan_public_hygiene",
    "score_synthetic_usefulness",
    "subject_can_act_for_agent",
    "synthetic_project_doc_fixture_allowlist",
    "synthetic_safe_content_provider",
    "validate_bounded_runner_config",
    "validate_l6_custody_receipt_noop_fixture",
    "validate_l6_positive_authorization_approval_context",
    "validate_l6_positive_authorization_receipt_result",
    "validate_l6_write_custody_approval_fixture",
    "validate_l6_write_custody_operation_class_fixture",
    "validate_l6_write_custody_rollback_audit_fixture",
    "validate_l6_write_intent_approval_context",
    "validate_l6_write_intent_preflight_gate_result",
    "with_request_identity",
    "verify_l5_post_read_receipt",
    "verify_l5_receipt_document",
]
